### ISSUE TITLE
Subpath reverse proxy support

### ISSUE THREAD

**Issue by fallenleavesgocrunch** [plexguide/Huntarr.io#130]
Currently the routing.py has hard coded / at the start of all the URLs. Could you remove that so I can host this thing behind a reverse proxy on a subpath, eg: http://mystuff.secretdomain.xyz/huntarr

**Comment by Gykes** [comment]
Would you be able to test this PR for me? 

https://github.com/plexguide/Huntarr.io/pull/154

It is possible a fix for your issue

**Comment by fallenleavesgocrunch** [comment]
Gave it a go - it redirects to /login

URL: https://<something>/huntarr/
302 /login

URL: https://<something>/login
404

This seems to come from src/primary/auth.py line 268 -- there are a few other places in here that would have a similar problem such as /setup.

**Comment by Gykes** [comment]
Ah, yea forgot to change all the reroutes.  Will do that in a bit after dinner

**Comment by Admin9705** [comment]
@Gykes glad your on the case!

**Comment by Gykes** [comment]
Yep, I'll look at it again when I get home today.

**Comment by stanthewizzard** [comment]
same issue for me :)

**Comment by Admin9705** [comment]
@stanthewizzard @Gykes @fallenleavesgocrunch moved to here - https://plex.one/threads/subpath-reverse-proxy-support.44/

**Comment by Admin9705** [comment]
Team, 6.5.12 - has this fixed now. Please let me know if it doesn't work @stanthewizzard @Gykes @fallenleavesgocrunch 

This solution:

Properly detects the application's base path when behind a reverse proxy
Applies the correct prefix to all URLs and redirects
Avoids the circular dependency issue that caused the internal server error
Users will now be able to host Huntarr behind a reverse proxy with a custom subpath like:

CopyInsert
http://mystuff.secretdomain.xyz/huntarr
The fix is robust and follows Flask's recommended approach for handling applications in subpath deployments. It ensures all URLs and redirects respect the configured subpath, which was exactly what was requested in the issue.

**Comment by fallenleavesgocrunch** [comment]
What do I configure to set the base path? I see in the code 'script_root' but an environment variable doesn't seem to do the job and there's nothing in the UI to configure it?

**Comment by Admin9705** [comment]
@fallenleavesgocrunch what do you need for me to set this up correctly (since i dont use)? reopening.

**Comment by fallenleavesgocrunch** [comment]
It's the "Properly detects the application's base path when behind a reverse proxy" point that is confusing me. How does it do this? a setting somewhere? an environment variable?

If it's meant to get it from the http request is that a special header I need to add in the reverse proxy setup? caddy doesn't seem to provide what you're looking for out of the box.

I added script_root as a header:

handle /huntarr/* {
    reverse_proxy http://huntarr:9705 {
        header_up script_root "/huntarr/"
    }
}

This doesn't seem to change anything.

**Comment by scr4tchy** [comment]
I've tried a few different ways with the latest version, but nothing seems to work:

```
    location /huntarr {
      proxy_pass http://huntarr:9705/huntarr;
```

```
    location /huntarr {
      proxy_pass http://huntarr:9705;
```

```
    location /huntarr/ {
      proxy_pass http://huntarr:9705/huntarr/;
```

Always my calls to `/huntarr/setup` get instantly redirected to `/setup` ...

**Comment by Admin9705** [comment]
@scr4tchy @vipergts450 @fallenleavesgocrunch @stanthewizzard @Gykes - would you be able to test since I do not run one. Will be out in 7.0.3+

<img width="864" alt="Image" src="https://github.com/user-attachments/assets/e1ea18ee-4153-4f01-aacc-ae4b96810946" />

**Comment by vipergts450** [comment]
What is the environment variable for this? `APPLICATION_ROOT` or `BASE_URL` or other? Since we cannot get to the UI at all, it needs to be set in the `compose.yml` file.

**Comment by vipergts450** [comment]
I manually edited `default.json` to amend the `base_url` variable, and we're closer, but now getting error "TOO_MANY_REDIRECTS" when it attempts to load https://domain.com/huntarr/setup.

**Comment by vipergts450** [comment]
Console doesn't even receive data at this point, it's entirely blank on reload.

![Image](https://github.com/user-attachments/assets/02dcd4b1-ce13-4c9f-a2fc-afc5759ede8f)

**Comment by vipergts450** [comment]
After a small tweak to my reverse proxy, I now get a 404 error at `/huntarr/setup`. This one appears to come from the app itself.

![Image](https://github.com/user-attachments/assets/e24afea9-41e1-4337-9aba-0074df762b7f)

**Comment by Admin9705** [comment]
ok @vipergts450 that helps. I'll try something later, and we'll create a separate container that we can tweak, somewhat hard when I don't run the setup.

**Comment by scr4tchy** [comment]
So awesome. Getting much closer 🙏 

`GET /huntarr/setup` returns `302 Found` with a `Location: /huntarr/setup` header...

**Comment by vipergts450** [comment]
> So awesome. Getting much closer 🙏
> 
> `GET /huntarr/setup` returns `302 Found` with a `Location: /huntarr/setup` header...

Can I ask which nginx location block got you there? I see you posted 3 earlier which hadn't been working? I'd like to try as well.

**Comment by vipergts450** [comment]
Actually, I am at the same point as you @scr4tchy . The initial connection works, it's the redirect to `/setup` that is broken.

```
# curl -vv https://<domain>/huntarr

> GET /huntarr/ HTTP/2
> Host: <domain>
> user-agent: curl/7.88.1
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 302
< server: openresty
< date: Mon, 19 May 2025 20:41:39 GMT
< content-type: text/html; charset=utf-8
< content-length: 215
< location: /huntarr/setup
< strict-transport-security: max-age=63072000;includeSubDomains; preload
<
<!doctype html>
<html lang=en>
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to the target URL: <a href="/huntarr/setup">/huntarr/setup</a>. If not, click the link.
* Connection #0 to host <domain> left intact
```

**Comment by scr4tchy** [comment]
@vipergts450 I use the following at the moment:

```
    set $upstream_huntarr huntarr:9705;
    location /huntarr {    
      proxy_pass http://$upstream_huntarr;
    }
```

This is the block I typically use for the other dozen *rr apps I have configured on this domain. The `set $upstream_huntarr` line can be removed safely if you don't like it, with `proxy_pass http://huntarr:9705` used instead of `proxy_pass http://$upstream_huntarr` but this allows nginx/openresty to be resilient to container restarts / ip changes.

**Comment by stanthewizzard** [comment]
using caddy

```
grabbing.xxxxx.com {
	tls /root/SSL/sdskh.com/fullchain.pem /root/SSL/sdskh.com/sdskh.com.key
	import secure *
	import encode *
	reverse_proxy docker20grabber.HQC.STARFLEET.DOM8:8085
	reverse_proxy /lidarr* docker20grabber.HQC.STARFLEET.DOM8:8686
	reverse_proxy /prowlarr* docker20grabber.HQC.STARFLEET.DOM8:9696
	reverse_proxy /radarr* docker20grabber.HQC.STARFLEET.DOM8:7878
	reverse_proxy /sonarr* docker20grabber.HQC.STARFLEET.DOM8:8989
	reverse_proxy /huntarr* docker20grabber.HQC.STARFLEET.DOM8:9705
	reverse_proxy /maintainerr* docker20grabber.HQC.STARFLEET.DOM8:6246
	reverse_proxy /transmission* docker20grabber.HQC.STARFLEET.DOM8:9091
	reverse_proxy /sabnzbd* docker20grabber.HQC.STARFLEET.DOM8:8080
}
```
Every subpath is ok
except for huntarr

http://192.168.0.35:9705/huntarr/login
ERR_TOO_MANY_REDIRECTS

https://grabbing.xxxxx.com/huntarr
ERR_TOO_MANY_REDIRECTS

**Comment by marlemion** [comment]
Same here on apache and latest docker huntarr

```
# -*- apache -*-

Servername xxx.net
ProxyPreserveHost On

<Location /huntarr/>
        ProxyPass http://192.168.178.20:9705/huntarr/
        ProxyPassReverse http://192.168.178.20:9705/huntarr/
</Location>
```

Results in ERR_TOO_MANY_REDIRECTS

**Comment by scr4tchy** [comment]
See https://github.com/plexguide/Huntarr.io/pull/497

**Comment by Admin9705** [comment]
@fallenleavesgocrunch @marlemion @stanthewizzard @vipergts450 @Gykes - @scr4tchy fixed it and released in 7.2.2 - please confirm working before closing this

**Comment by Admin9705** [comment]
@vipergts450 @stanthewizzard - 100% @scr4tchy for working a miracle on this, think i would have never gotten it. i'll keep this open until all the issues rooted out. @scr4tchy do you see the issue @vipergts450 is speaking of?

**Comment by vipergts450** [comment]
Some more missing subpaths in various references to static files.

From my Chrome console:

```
variables.css:1  Failed to load resource: the server responded with a status of 404 ()
styles.css:1  Failed to load resource: the server responded with a status of 404 ()
variables.css:1  Failed to load resource: the server responded with a status of 404 ()
styles.css:1  Failed to load resource: the server responded with a status of 404 ()

static/data/sleep.json?t=1748028795044:1 
          Failed to load resource: the server responded with a status of 400 ()
direct-reset.js:17 Stateful header not found, will try again in 1 second
cycle-countdown.js:104 
GET https://apps.230.bklynite.com/static/data/sleep.json?t=1748028915027 400 (Bad Request)
```

**Comment by marlemion** [comment]
It is also working for me.

**Comment by fallenleavesgocrunch** [comment]
Success here. Using caddy.

**Comment by scr4tchy** [comment]
> Setup completes ok. The final button "Go to Dashboard" however misses the redirect to the /huntarr subpath. So that one button needs to be updated to be aware of the subpath. Going to https://domain/huntarr manually then loads correctly!

Thank you, fixed.

> variables.css:1  Failed to load resource: the server responded with a status of 404 ()

Not related, the file doesn't exist. I've removed the reference.

> styles.css:1  Failed to load resource: the server responded with a status of 404 ()

Not related, the file doesn't exist. I've renamed the reference.

**Comment by vipergts450** [comment]
@scr4tchy Do you mind checking paths in `cycle-countdown.js` in `frontend/js`  ? I think this is not loading either.

**Comment by scr4tchy** [comment]
>  Is there a mini guide one of you can write up real quick so i can put it in the wiki docs

@Admin9705 

We recommend Huntarr to run on a dedicated subdomain (e.g. `huntarr.my-home.com`). If however you'd like to make it available on a subpath of a shared subdomain (e.g. `plex.my-home.com/huntarr`), you can follow those steps:

- Create a `settings/general.json` file under the configuration directory of Huntarr with the following content. If you had already started Huntarr and the file exists, simplify modify the setting below accordingly.
```
{
  "base_url": "/huntarr"
}
```
- Configure your reverse proxy to route "/huntarr" to the Huntarr service, e.g. with nginx and a container named `huntarr`:
```
    set $upstream_huntarr huntarr:9705;
    location /huntarr {
      proxy_pass http://$upstream_huntarr;
    }
```
- Start Huntarr (or restart it if it was already running)
- Open the URL where Huntarr runs, and proceed with the Setup normally

> @scr4tchy Do you mind checking paths in cycle-countdown.js in frontend/js ? I think this is not loading either.

Loads fine for me

![Image](https://github.com/user-attachments/assets/1e8b8f9e-39c6-4f36-8614-5260870f185b)

**Comment by vipergts450** [comment]
Interesting. Mine doesn't load.

![Image](https://github.com/user-attachments/assets/0a00cc3b-90bc-4012-9a0b-7cea19f29c57)

**Comment by scr4tchy** [comment]
@vipergts450 

Yep, same here, but I couldn't tell ya why it doesn't work. The js file prints logs (but no errors):
```
[CycleCountdown] Initializing countdown timers
cycle-countdown.js:302 [CycleCountdown] Applied app-specific styling class: sonarr
cycle-countdown.js:307 [CycleCountdown] Timer created for sonarr next to reset button
cycle-countdown.js:302 [CycleCountdown] Applied app-specific styling class: radarr
cycle-countdown.js:307 [CycleCountdown] Timer created for radarr next to reset button
cycle-countdown.js:302 [CycleCountdown] Applied app-specific styling class: lidarr
cycle-countdown.js:307 [CycleCountdown] Timer created for lidarr next to reset button
cycle-countdown.js:302 [CycleCountdown] Applied app-specific styling class: readarr
cycle-countdown.js:307 [CycleCountdown] Timer created for readarr next to reset button
cycle-countdown.js:302 [CycleCountdown] Applied app-specific styling class: whisparr
cycle-countdown.js:307 [CycleCountdown] Timer created for whisparr next to reset button
cycle-countdown.js:253 [CycleCountdown] Reset button not found for whisparr-v3
cycle-countdown.js:287 [CycleCountdown] Applied Whisparr V3 (eros) styling
cycle-countdown.js:302 [CycleCountdown] Applied app-specific styling class: eros
cycle-countdown.js:307 [CycleCountdown] Timer created for eros next to reset button
```

Can you confirm it works in this version without subpath?

**Comment by vipergts450** [comment]
Could it be the call to /static/sleep.js?

**Comment by scr4tchy** [comment]
@vipergts450 Yeah correct, thanks. Fixed in my PR now~

**Comment by vipergts450** [comment]
Before you do, it looks like there was a regression in `cycle-countdown.js` because it no longer has the correct reference to `./static/data/sleep.json` and the countdown timer is broken again. I can't seem to see when the regression happened.

**Comment by vipergts450** [comment]
Thank you again to @scr4tchy for your contributions and @Admin9705 for enabling this convenience for us.

**Comment by aniqueta** [comment]
Thanks for adding this feature. I'm not sure why, but in 7.6.1, this doesn't work with the macOS releases, but it does from Docker. Same nginx config and subpath config in Huntarr (showing in settings interface post app restart).

**Comment by vipergts450** [comment]
> Thanks for adding this feature. I'm not sure why, but in 7.6.1, this doesn't work with the macOS releases, but it does from Docker. Same nginx config and subpath config in Huntarr (showing in settings interface post app restart).

Looks like the offending line is still present in `cycle-countdown.js` possibly because of the `buildUrl` function:

```
// Use a completely relative URL approach to avoid any subpath issues
            const url = buildUrl('./api/cycle/status');

```

I think `buildUrl` should reference the Subpath variable set in the Settings page rather than using the . notation, because this seems to try to call `https://domain/api/cycle/status` which fails with Return Code 400 instead of `https://domain/subpath/api/cycle/status`.

**Comment by stanthewizzard** [comment]
Hello
opening it again
in latest version 8.1.11
/huntarr subpath doesn't work anymore

Thanks for help
